// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="PrintRequestAndStatus.cs">
//   
// </copyright>
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
// <summary>
//   The wells fargo ufeds.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace WF.EAI.BLL.cas.Print
{
    using System.Xml.Serialization;

    /// <summary>
    /// The wells fargo ufeds.
    /// </summary>
    public class WellsFargoUFEDS
    {
        #region Fields

        /// <summary>
        /// The msg body.
        /// </summary>
        public MsgBody msgBody;

        /// <summary>
        /// The msg header.
        /// </summary>
        public MsgHeader msgHeader;

        #endregion
    }

    /// <summary>
    /// The msg header.
    /// </summary>
    public class MsgHeader
    {
        #region Fields

        /// <summary>
        /// The context id.
        /// </summary>
        public string contextId;

        /// <summary>
        /// The date.
        /// </summary>
        public string date;

        /// <summary>
        /// The environment.
        /// </summary>
        public string environment;

        /// <summary>
        /// The message name.
        /// </summary>
        public string messageName;

        /// <summary>
        /// The sender.
        /// </summary>
        public string sender;

        /// <summary>
        /// The sequence num.
        /// </summary>
        public string sequenceNum;

        /// <summary>
        /// The time.
        /// </summary>
        public string time;

        /// <summary>
        /// The user id.
        /// </summary>
        public string userId;

        /// <summary>
        /// The version num.
        /// </summary>
        public string versionNum;

        #endregion
    }

    /// <summary>
    /// The msg body.
    /// </summary>
    public class MsgBody
    {
        #region Fields

        /// <summary>
        /// The activity code.
        /// </summary>
        public string activityCode;

        /// <summary>
        /// The application id.
        /// </summary>
        public string applicationID;

        /// <summary>
        /// The description list.
        /// </summary>
        [XmlArray]
        [XmlArrayItem("description")]
        public string[] descriptionList;

        /// <summary>
        /// The doc type.
        /// </summary>
        public string docType;

        /// <summary>
        /// The message.
        /// </summary>
        public string message;

        /// <summary>
        /// The print au.
        /// </summary>
        public string printAU;

        /// <summary>
        /// The print user id.
        /// </summary>
        public string printUserID;

        #endregion
    }
}