//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentResult
    {
        public tbl_StudentResult()
        {
            this.tbl_YearAcademy = new HashSet<tbl_YearAcademy>();
        }
    
        public int Id_StudentResult { get; set; }
        public Nullable<int> Id_Student { get; set; }
        public Nullable<int> Id_Course { get; set; }
    
        public virtual ICollection<tbl_YearAcademy> tbl_YearAcademy { get; set; }
    }
}
