//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nationality
    {
        public tbl_Nationality()
        {
            this.tbl_ContactDetail = new HashSet<tbl_ContactDetail>();
            this.tbl_ContactDetail1 = new HashSet<tbl_ContactDetail>();
        }
    
        public int Id_Nationality { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<tbl_ContactDetail> tbl_ContactDetail { get; set; }
        public virtual ICollection<tbl_ContactDetail> tbl_ContactDetail1 { get; set; }
    }
}
