//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactDetail
    {
        public tbl_ContactDetail()
        {
            this.tbl_Student = new HashSet<tbl_Student>();
        }
    
        public int Id_ContactDetail { get; set; }
        public string c_flatNo { get; set; }
        public string c_building { get; set; }
        public string c_area { get; set; }
        public string c_dist { get; set; }
        public string c_zipcode { get; set; }
        public Nullable<int> Id_Nationality { get; set; }
        public string c_phoneno { get; set; }
        public string p_flatno { get; set; }
        public string p_building { get; set; }
        public string p_area { get; set; }
        public string p_dist { get; set; }
        public string p_zipcode { get; set; }
        public Nullable<int> p_Id_Nationality { get; set; }
        public string p_phoneno { get; set; }
    
        public virtual tbl_Nationality tbl_Nationality { get; set; }
        public virtual tbl_Nationality tbl_Nationality1 { get; set; }
        public virtual ICollection<tbl_Student> tbl_Student { get; set; }
    }
}
