//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Salary
    {
        public tbl_Salary()
        {
            this.tbl_EmploymentHistory = new HashSet<tbl_EmploymentHistory>();
        }
    
        public int Id_Salary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> Compensation { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> YearlyIncome { get; set; }
        public Nullable<decimal> Taxes1 { get; set; }
        public Nullable<decimal> Taxes2 { get; set; }
        public Nullable<decimal> Taxes3 { get; set; }
        public Nullable<decimal> Taxes4 { get; set; }
        public Nullable<decimal> Taxes5 { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> OtherIncome { get; set; }
    
        public virtual ICollection<tbl_EmploymentHistory> tbl_EmploymentHistory { get; set; }
    }
}
