//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int Id_Student { get; set; }
        public string GRNO { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<int> MaleFemale { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Id_Language { get; set; }
        public Nullable<int> Id_CastReligion { get; set; }
        public Nullable<int> Id_ContactDetail { get; set; }
        public Nullable<int> Id_ParentDetail { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string BloodGroup { get; set; }
        public string PictureURL { get; set; }
        public byte[] AboutMe { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual tbl_CastReligion tbl_CastReligion { get; set; }
        public virtual tbl_ContactDetail tbl_ContactDetail { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_language tbl_language { get; set; }
        public virtual tbl_ParentDetail tbl_ParentDetail { get; set; }
    }
}
