//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public int Id_Account { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public Nullable<int> Id_YearAcademy { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_YearAcademy tbl_YearAcademy { get; set; }
    }
}
