//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_YearAcademy
    {
        public tbl_YearAcademy()
        {
            this.tbl_ClassLevel = new HashSet<tbl_ClassLevel>();
            this.tbl_MasterFee = new HashSet<tbl_MasterFee>();
            this.tbl_Account = new HashSet<tbl_Account>();
        }
    
        public int Id_YearAcademy { get; set; }
        public Nullable<int> Id_Student { get; set; }
        public string FromToYear { get; set; }
        public string Division { get; set; }
        public Nullable<int> RollNo { get; set; }
        public Nullable<int> Id_StudentResult { get; set; }
        public Nullable<int> Id_ClassLevel { get; set; }
        public Nullable<int> Id_Transport { get; set; }
    
        public virtual ICollection<tbl_ClassLevel> tbl_ClassLevel { get; set; }
        public virtual tbl_ClassLevel tbl_ClassLevel1 { get; set; }
        public virtual ICollection<tbl_MasterFee> tbl_MasterFee { get; set; }
        public virtual tbl_StudentResult tbl_StudentResult { get; set; }
        public virtual tbl_Transport tbl_Transport { get; set; }
        public virtual ICollection<tbl_Account> tbl_Account { get; set; }
    }
}
