//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public tbl_Employee()
        {
            this.tbl_EmploymentHistory1 = new HashSet<tbl_EmploymentHistory>();
            this.tbl_Student = new HashSet<tbl_Student>();
            this.tbl_Account = new HashSet<tbl_Account>();
        }
    
        public int Id_Employee { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_EmploymentHistory { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string AccessURL { get; set; }
    
        public virtual tbl_EmploymentHistory tbl_EmploymentHistory { get; set; }
        public virtual ICollection<tbl_EmploymentHistory> tbl_EmploymentHistory1 { get; set; }
        public virtual ICollection<tbl_Student> tbl_Student { get; set; }
        public virtual ICollection<tbl_Account> tbl_Account { get; set; }
    }
}
