//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_language
    {
        public tbl_language()
        {
            this.tbl_Student = new HashSet<tbl_Student>();
        }
    
        public int Id_language { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tbl_Student> tbl_Student { get; set; }
    }
}
