//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmploymentHistory
    {
        public tbl_EmploymentHistory()
        {
            this.tbl_Employee = new HashSet<tbl_Employee>();
        }
    
        public int Id_EmploymentHistory { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> Id_Salary { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
        public Nullable<System.DateTime> DateLeaving { get; set; }
        public string HighestQualification { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual ICollection<tbl_Employee> tbl_Employee { get; set; }
        public virtual tbl_Employee tbl_Employee1 { get; set; }
        public virtual tbl_Salary tbl_Salary { get; set; }
    }
}
