// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="AccountDetails.cs">
//   
// </copyright>
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
// <summary>
//   The koa c 001.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace WF.EAI.BLL.cas.Services
{
    using System;
    using System.Xml.Serialization;

    /// <summary>
    /// The koa c 001.
    /// </summary>
    [XmlRoot(Namespace = "", IsNullable = false)]
    [Serializable]
    public class KOAC001
    {
        #region Fields

        /// <summary>
        /// The body.
        /// </summary>
        public Body Body;

        /// <summary>
        /// The header.
        /// </summary>
        public Header Header;

        /// <summary>
        /// The version.
        /// </summary>
        [XmlAttribute]
        public string version;

        #endregion

        #region Public Methods and Operators

        /// <summary>
        /// The get accoun view id.
        /// </summary>
        /// <param name="hoganProductCode">
        /// The hogan product code.
        /// </param>
        /// <returns>
        /// The <see cref="string"/>.
        /// </returns>
        public string GetAccounViewID(string hoganProductCode)
        {
            switch (hoganProductCode)
            {
                case "DDA":
                    return "ACCTDETAIL04";
                case "ILA":
                    return "ACCTDETAIL07";
                case "XCC":
                    return "ACCTDETAIL03";
                case "XIV":
                    return "ACCTDETAIL02";
                case "LCA":
                    return "ACCTDETAIL08";
                case "CDA":
                    return "ACCTDETAIL05";
                case "REA":
                    return "ACCTDETAIL06";
                case "XML":
                    return "ACCTDETAIL01";
                default:
                    return string.Empty;
            }
        }

        #endregion
    }
}