<?php
$FixedCategory = array("Agriculture",
        "Air Condition",
        "Apparels",
        "Application",
        "Astrology",
        "ATMs",
        "Automobile",
        "Baby School",
        "Bag",
        "Bungalow",
        "Bank",
        "Banner",
        "Banquets",
        "Beauty Spa",
        "Beer",
        "Blub",
        "Blubs",
        "Books",
        "Burgha",
        "Bus",
        "Bus Ticketing",
        "Cab",
        "Cable",
        "Cake",
        "Calendar",
        "Car",
        "Car Hire",
        "Chemists",
        "Cinema",
        "Clubs",
        "Company",
        "Computers",
        "Consultants",
        "Cookery",
        "Courier",
        "Currency",
        "Dancing",
        "Diet",
        "School",
        "Doctors",
        "Classes",
        "Dumper",
        "Education",
        "Theatre",
        "Electronics",
        "Emergency",
        "Engineer",
        "Entertainment",
        "Essentials",
        "Events",
        "Exchange rate",
        "Fitness",
        "Flight",
        "Flowers",
        "Food",
        "Furniture",
        "Gas",
        "Gems Jewellery",
        "Gifts",
        "Glasses",
        "Gold",
        "Government",
        "Grocery",
        "Gym",
        "handyman",
        "Hardware",
        "Hardware shop",
        "Hire",
        "Hire cab",
        "Hobby classes",
        "Home",
        "Hospitals",
        "Hotels",
        "Industries",
        "institution",
        "Internet",
        "Internet Services",
        "Jobs",
        "Lab",
        "Ladies Bag",
        "Library",
        "Lodge",
        "Looking For Mate",
        "Machines",
        "Mall",
        "Mechanic",
        "Medicine",
        "Mobile Battery",
        "Mobile Phones",
        "Mobile Repair",
        "Mobile Shop",
        "Motor",
        "Motor Learning",
        "Motor Repair",
        "Movies",
        "My Favorites",
        "Nightlife",
        "Office",
        "Packer mover",
        "Party",
        "Passport",
        "Personal Finance",
        "Petrol Pumps",
        "Pest",
        "Pets",
        "Pipe",
        "Pizza",
        "Quran",
        "Rainy Season",
        "Real Estate",
        "Recharge",
        "Repairs",
        "Resorts",
        "Rest area",
        "Restaurants",
        "Restroom",
        "Road Repair",
        "Room",
        "Science Lab",
        "Security",
        "Shop Online",
        "Sports",
        "Sports bike",
        "Station",
        "Taxis",
        "Telephone",
        "Tiffin",
        "Towing",
        "Travel Bags",
        "Tuition",
        "Tv",
        "Vacuum",
        "Video Camera",
        "Washing Machine",
        "Water",
        "Wedding",
        "Western Union",
        "Wine",
        "Xerox",
        "Yoga",
        "Zomba");
?>